/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * API description
 * OpenAPI spec version: 0.1
 */

export interface CreatePatientDto {
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  phoneNumber: string;
  /** @nullable */
  email?: string | null;
}
