/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * API description
 * OpenAPI spec version: 0.1
 */

export interface Meta {
  total: number;
  lastPage: number;
  currentPage: number;
  perPage: number;
  /** @nullable */
  prev: number | null;
  /** @nullable */
  next: number | null;
}
