/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * API description
 * OpenAPI spec version: 0.1
 */
import type { Meta } from './meta';
import type { Patient } from './patient';

export interface PaginatedPatientOutput {
  meta: Meta;
  data: Patient[];
}
