/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * API description
 * OpenAPI spec version: 0.1
 */
import type { Visit } from './visit';

export interface Patient {
  id: string;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  phoneNumber: string;
  /** @nullable */
  email?: string | null;
  visits?: Visit[];
  createdAt: string;
  updatedAt: string;
}
