/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * API description
 * OpenAPI spec version: 0.1
 */

export type VisitStatus = typeof VisitStatus[keyof typeof VisitStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VisitStatus = {
  SCHEDULED: 'SCHEDULED',
  CANCELED: 'CANCELED',
  COMPLETED: 'COMPLETED',
} as const;
